"""empty message

Revision ID: 1152d90f591
Revises: 39e254fef51
Create Date: 2015-12-10 16:49:17.633987

"""

# revision identifiers, used by Alembic.
revision = '1152d90f591'
down_revision = '39e254fef51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
