"""empty message

Revision ID: 22e2ae877b1
Revises: 4ac62aa1c09
Create Date: 2015-12-23 23:37:31.091246

"""

# revision identifiers, used by Alembic.
revision = '22e2ae877b1'
down_revision = '4ac62aa1c09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
