"""empty message

Revision ID: 3011183fd52
Revises: 22e2ae877b1
Create Date: 2015-12-24 21:08:19.063239

"""

# revision identifiers, used by Alembic.
revision = '3011183fd52'
down_revision = '22e2ae877b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
