"""empty message

Revision ID: 39e254fef51
Revises: 2180daaa7ba
Create Date: 2015-12-10 00:45:12.490942

"""

# revision identifiers, used by Alembic.
revision = '39e254fef51'
down_revision = '2180daaa7ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
