"""empty message

Revision ID: 3bf4fbc561f
Revises: 1152d90f591
Create Date: 2015-12-10 16:49:22.525490

"""

# revision identifiers, used by Alembic.
revision = '3bf4fbc561f'
down_revision = '1152d90f591'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
