"""empty message

Revision ID: 3bfdc606e43
Revises: 3bf4fbc561f
Create Date: 2015-12-11 13:20:05.499937

"""

# revision identifiers, used by Alembic.
revision = '3bfdc606e43'
down_revision = '3bf4fbc561f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
